/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

import controller.*;
import java.util.ArrayList;
import model.*;

/**
 *
 * @author Dev-Otávio
 */
public class CadastrarPedido extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPedido
     */
    
    CadastroClientes cliente = new CadastroClientes();
    CadastroFuncionarios funcionario = new CadastroFuncionarios();
    CadastroProdutos produto = new CadastroProdutos();
    CadastroPedidos pedido = new CadastroPedidos();
    
    public CadastrarPedido() {
        initComponents();
        this.jLabelFoundCliente.setVisible(false);
        this.jLabelFoundFuncionario.setVisible(false);
        this.jLabelFoundProduto.setVisible(false);
        this.jLabelStatus.setVisible(false);
        this.jLabelPedidoRemovido.setVisible(false);
        this.jButtonRemover.setVisible(false);
        this.jButtonNovoPedido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCliente = new javax.swing.JTextField();
        jButtonCliente = new javax.swing.JButton();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jTextFieldFuncionario = new javax.swing.JTextField();
        jButtonFuncionario = new javax.swing.JButton();
        jLabelFuncionario = new javax.swing.JLabel();
        jButtonRealizarPedido = new javax.swing.JButton();
        jTextFieldProduto = new javax.swing.JTextField();
        jButtonProduto = new javax.swing.JButton();
        jLabelProduto = new javax.swing.JLabel();
        jLabelFoundCliente = new javax.swing.JLabel();
        jLabelFoundFuncionario = new javax.swing.JLabel();
        jLabelFoundProduto = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jButtonRemover = new javax.swing.JButton();
        jLabelPedidoRemovido = new javax.swing.JLabel();
        jButtonNovoPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCliente.setText("Buscar");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jLabelCliente.setText("Cliente");

        jLabelData.setText("Data");

        jButtonFuncionario.setText("Buscar");
        jButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioActionPerformed(evt);
            }
        });

        jLabelFuncionario.setText("Funcionário");

        jButtonRealizarPedido.setText("Fazer Pedido");
        jButtonRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarPedidoActionPerformed(evt);
            }
        });

        jButtonProduto.setText("Buscar");
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });

        jLabelProduto.setText("Filme");

        jLabelFoundCliente.setText("Encontrado!");

        jLabelFoundFuncionario.setText("Encontrado!");

        jLabelFoundProduto.setText("Encontrado!");

        jLabelStatus.setText("Preencha os Campos!");

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabelPedidoRemovido.setText("Pedido Removido!");

        jButtonNovoPedido.setText("Novo Pedido");
        jButtonNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFoundCliente)
                            .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFuncionario)
                            .addComponent(jLabelProduto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFoundProduto)
                            .addComponent(jLabelFoundFuncionario)
                            .addComponent(jButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPedidoRemovido))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelStatus)))
                        .addGap(29, 29, 29)
                        .addComponent(jButtonNovoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jLabelFoundCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jTextFieldCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncionario)
                    .addComponent(jLabelFoundFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProduto)
                    .addComponent(jLabelFoundProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLabelPedidoRemovido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonNovoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        // TODO add your handling code here:
        cliente.setListaClientes(new ArrayList<Cliente>());
        cliente.buscar(this.jTextFieldCliente.getText());
        
        if (cliente.getListaClientes().size() == 1) {
            this.jLabelFoundCliente.setVisible(true);
        }
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioActionPerformed
        // TODO add your handling code here:
        funcionario.setListaFuncionarios(new ArrayList<Funcionario>());
        funcionario.buscar(this.jTextFieldFuncionario.getText());
        
        if (funcionario.getListaFuncionarios().size() == 1) {
            this.jLabelFoundFuncionario.setVisible(true);
        } else if (funcionario.getListaFuncionarios().size() == 0) {
            this.jLabelFoundFuncionario.setVisible(true);
            this.jLabelFoundFuncionario.setText("Funcionário não encontrado!");
        }
    }//GEN-LAST:event_jButtonFuncionarioActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        // TODO add your handling code here:
        produto.setListaProdutos(new ArrayList<Produto>());
        produto.buscar(this.jTextFieldProduto.getText());
        
        if (produto.getListaProdutos().size() == 1) {
            this.jLabelFoundProduto.setVisible(true);
        } else if (produto.getListaProdutos().size() == 0) {
            this.jLabelFoundProduto.setVisible(true);
            this.jLabelFoundProduto.setText("Produto não encontrado!");
        }
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarPedidoActionPerformed
        // TODO add your handling code here:
        if (cliente.getListaClientes().size() > 0 || funcionario.getListaFuncionarios().size() > 0 || produto.getListaProdutos().size() > 0) {
            Pedido ped = new Pedido(cliente.getListaClientes().get(0), this.jTextFieldData.getText(), funcionario.getListaFuncionarios().get(0), produto.getListaProdutos().get(0));
            if (pedido.adicionarPedido(ped)) {
                this.jLabelStatus.setVisible(true);
                this.jLabelStatus.setText("Salvo com sucesso!");
                this.jButtonRemover.setVisible(true);
                this.jButtonNovoPedido.setVisible(true);
//                this.setVisible(false);
            } else {
                this.jLabelStatus.setVisible(true);
                this.jLabelStatus.setText("Houve um erro na gravação do Pedido");
            }
        } else {
            this.jLabelStatus.setVisible(true);
        }
    }//GEN-LAST:event_jButtonRealizarPedidoActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        pedido.removerPedido(cliente.getListaClientes().get(0));
        this.jButtonRealizarPedido.setVisible(false);
        this.jLabelStatus.setVisible(false);
        this.jLabelPedidoRemovido.setVisible(true);
        this.jButtonNovoPedido.setVisible(true);
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoPedidoActionPerformed
        // TODO add your handling code here:
        this.jLabelPedidoRemovido.setVisible(false);
        this.jButtonRealizarPedido.setVisible(false);
        this.jTextFieldCliente.setText("");
        this.jTextFieldFuncionario.setText("");
        this.jTextFieldProduto.setText("");
        this.jTextFieldData.setText("");
        produto = new CadastroProdutos();
        cliente = new CadastroClientes();
        funcionario = new CadastroFuncionarios();
        pedido = new CadastroPedidos();
        this.jButtonNovoPedido.setVisible(false);
        this.jButtonRemover.setVisible(false);
        this.jButtonRealizarPedido.setVisible(true);
        this.jLabelStatus.setVisible(false);
        this.jLabelFoundCliente.setVisible(false);
        this.jLabelFoundFuncionario.setVisible(false);
        this.jLabelFoundProduto.setVisible(false);
    }//GEN-LAST:event_jButtonNovoPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPedido().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonFuncionario;
    private javax.swing.JButton jButtonNovoPedido;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonRealizarPedido;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFoundCliente;
    private javax.swing.JLabel jLabelFoundFuncionario;
    private javax.swing.JLabel jLabelFoundProduto;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelPedidoRemovido;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldFuncionario;
    private javax.swing.JTextField jTextFieldProduto;
    // End of variables declaration//GEN-END:variables
}
