-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 17:28:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancoLocadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancoLocadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoLocadora` DEFAULT CHARACTER SET utf8 ;
USE `bancoLocadora` ;

-- -----------------------------------------------------
-- Table `bancoLocadora`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Cliente_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bancoLocadora`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Domicilio` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Domicilio` (
  `idDomicilio` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`DomicilioPessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`DomicilioPessoa` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`DomicilioPessoa` (
  `Pessoa_idPessoa` INT NOT NULL,
  `Domicilio_idDomicilio` INT NOT NULL,
  `principal` TINYINT NOT NULL,
  PRIMARY KEY (`Pessoa_idPessoa`, `Domicilio_idDomicilio`),
  INDEX `fk_Pessoa_has_Domicilio_Domicilio1_idx` (`Domicilio_idDomicilio` ASC),
  INDEX `fk_Pessoa_has_Domicilio_Pessoa_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Pessoa_has_Domicilio_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bancoLocadora`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Domicilio_Domicilio1`
    FOREIGN KEY (`Domicilio_idDomicilio`)
    REFERENCES `bancoLocadora`.`Domicilio` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `cnpf` VARCHAR(18) NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  INDEX `fk_Fornecedor_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Fornecedor_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bancoLocadora`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `carteiraTrabalho` VARCHAR(20) NOT NULL,
  `pisPasep` VARCHAR(20) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Funcionario_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `bancoLocadora`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Locacao` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Locacao` (
  `idLocacao` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idLocacao`),
  INDEX `fk_Locacao_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Locacao_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Locacao_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `bancoLocadora`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `bancoLocadora`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `dataDevolucao` DATETIME NOT NULL,
  `dataLocacao` DATETIME NOT NULL,
  `devolvido` TINYINT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `bancoLocadora`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`PedidosLocacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`PedidosLocacao` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`PedidosLocacao` (
  `Locacao_idLocacao` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Locacao_idLocacao`, `Pedido_idPedido`),
  INDEX `fk_Locacao_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC),
  INDEX `fk_Locacao_has_Pedido_Locacao1_idx` (`Locacao_idLocacao` ASC),
  CONSTRAINT `fk_Locacao_has_Pedido_Locacao1`
    FOREIGN KEY (`Locacao_idLocacao`)
    REFERENCES `bancoLocadora`.`Locacao` (`idLocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `bancoLocadora`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoLocadora`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoLocadora`.`Produto` ;

CREATE TABLE IF NOT EXISTS `bancoLocadora`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `disponivel` TINYINT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  INDEX `fk_Produto_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `bancoLocadora`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `bancoLocadora`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
